### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by janrinze** [daglem/reDIP-64#1]
Hi There,

Has this board been tested and does DP-Alt mode work?
I am very much interested in testing DP-Alt mode on the ECP5.

best regards,
Jan Rinze.

**Comment by daglem** [comment]
Hi Jan,

When I designed the board, several of the key components were unobtainium, and unfortunately I haven't gotten back to it yet. The board has thus never been tested, and since it's fairly complex there is a risk it won't work at all.

The only of my boards that's been thoroughly tested so far is the [reDIP
SID](https://github.com/daglem/reDIP-SID).

Best regards,
Dag
